error handling working but needs work

diff --git a/basic_error_handling b/basic_error_handling
--- a/basic_error_handling
+++ b/basic_error_handling
@@ -17,13 +17,21 @@
 # run some command
 
 
-status=$?
-if [ $status -eq 1 ]; then
-    echo "General error"
-elif [ $status -eq 2 ]; then
-    echo "Misuse of shell builtins"
-elif [ $status -eq 126 ]; then
-    echo "Command invoked cannot execute"
-elif [ $status -eq 128 ]; then
-    echo "Invalid argument"
-fi
+# status=$?
+# if [ $status -eq 1 ]; then
+#     echo "General error"
+# elif [ $status -eq 2 ]; then
+#     echo "Misuse of shell builtins"
+# elif [ $status -eq 126 ]; then
+#     echo "Command invoked cannot execute"
+# elif [ $status -eq 128 ]; then
+#     echo "Invalid argument"
+# fi
+
+# set -e
+# #
+# # some critical code block where no error is allowed
+# #
+# set +e
+
+
