better error handling

diff --git a/errE b/errE
--- a/errE
+++ b/errE
@@ -1,25 +1,22 @@
 #!/bin/bash
 
 
-
 # Include trybatch.sh as a library
-# shellcheck disable=SC1091
 source ./try_catch
 
 # Define custom exception types
-export PROFILER_ERR=100
-export CLOSE_ERR=101
-export INIT_ERR=102
+export ERR_BAD=100
+export ERR_WORSE=101
+export ERR_CRITICAL=102
 
 try
 (
 
-PID_CODE=$BASHPID
 
-#!/bin/bash
 
+set -o pipefail -e
 #inform user 
-sudo printf "\\nTo exit at any time type \"kill -USR1 %s\"" $PID_CODE
+sudo printf "\\nTo exit at any time type \"kill -USR1 %s\"" $$
 
 #trap signal, call close sequence
 trap close USR1
@@ -159,18 +156,18 @@ echo "$SECINC" "$CPU_av" >> ./logs/cpu_av.dat
 #inform user
 printf "\\n-  -  -   -   -   -   -   - EXITING - -   -   -   -   -   -   -   -  "
 
-#psercentages to graph display and save to png
-#plot cpu
-./gnuplot_scripts/cpu_util
+# #psercentages to graph display and save to png
+# #plot cpu
+# ./gnuplot_scripts/cpu_util
 
-#plot cpu and gpu temp
-./gnuplot_scripts/cpu_gpu_temp
+# #plot cpu and gpu temp
+# ./gnuplot_scripts/cpu_gpu_temp
 
-#plot memory in Gi
-./gnuplot_scripts/memory_Gi
+# #plot memory in Gi
+# ./gnuplot_scripts/memory_Gi
 
-#plot memory in Mi
-./gnuplot_scripts/memory_Mi
+# #plot memory in Mi
+# ./gnuplot_scripts/memory_Mi
 
 #delay to make sequence change obvious    
 sleep 1
@@ -207,8 +204,8 @@ if [[ -f ./logs/cpusys.dat && -f ./logs/mswfr.dat && -f ./logs/gputemp.dat && -f
 #inform user
 printf "\\ndata logs cleared"
 
-#clear old logs
-rm -r ./logs/*
+# #clear old logs
+# rm -r ./logs/*
 
 fi
 
@@ -287,15 +284,15 @@ fi
 #inform user
 printf "\\n-  -  -   -   -   -   -  - PROFILER RUNNING - -   -   -   -  -   -   -  -"
 printf "\\n-  -  -   -   -   -  - ENTER OR CTRL+Z FOR CONSOLE -  -   -    -   -   -  -"
-printf "\\n-   -  -  -TO EXIT TYPE \"kill -USR1 %s\" AND PRESS ENTER- -  -   -  -  -  -" $PID_CODE
+printf "\\n-   -  -  -TO EXIT TYPE \"kill -USR1 %s\" AND PRESS ENTER- -  -   -  -  -  -" $$
 printf  "\\n-  -  -   -   -   -  - ENTER OR CTRL+Z FOR CONSOLE -  -   -    -   -   -   -"
 
 
 #initiate increment
 SECINC=0
 
-#run led control script
-./led_control &
+# #run led control script
+# ./led_control &
 
 #loop functions to collect metrics every one second
 while true ; do
@@ -417,26 +414,39 @@ CPU_av=.$(echo "((($CPU_sy+$CPU_us)*100)/5)" | bc | cut -c1-2)
 echo "$SECINC" "$CPU_av" >> ./logs/cpu_av.dat
 
 #delay timer
-sleep 1
+sle7ep 1
 
 #increment seconds
 (( SECINC++ ))
 
 #loop complete
 done
+set +o pipefail +e
 
-    )|| throw $PROFILER_ERR
 
-
+)
 catch || {
-    # shellcheck disable=SC2154
-    case $exception_code in
-        $PROFILER_ERR)
+
+    echo bullshit $?
+
+
+case $exception_code in
+        $ERR_BAD)
             echo "This error is bad"
         ;;
+        $ERR_WORSE)
+            echo "This error is worse"
+        ;;
+        $ERR_CRITICAL)
+            echo "This error is critical"
+        ;;
         *)
-            echo "Unknown error: $?"
-            throw "$exit_code"    # re-throw an unhandled exception
+            echo "Unknown error: $exit_code"
+            throw $exit_code    # re-throw an unhandled exception
         ;;
     esac
+
+
+
+
 }
